version: 1.0.{build}.{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

init:
  #- mkdir C:\projects\ezWebSockify.deps\include
  #- mkdir C:\projects\ezWebSockify.deps\src
  #- cd C:\projects\ezWebSockify.deps\src
  #- appveyor DownloadFile "https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.7z"
  #- 7z x boost_1_73_0.7z
  #- cd boost_1_73_0
  #- move boost C:\projects\ezWebSockify.deps\include\
  #- mkdir C:\projects\ezWebSockify.deps\include\nlohmann
  #- cd C:\projects\ezWebSockify.deps\include\nlohmann
  #- appveyor DownloadFile "https://github.com/nlohmann/json/releases/download/v3.9.1/json.hpp"
  #- cd %APPVEYOR_BUILD_FOLDER%
  
build:
  project: %APPVEYOR_BUILD_FOLDER%\platform\windows\ezWebSockify.sln

# scripts to run before build
before_build: 
  #- .\platform\windows\before_build.bat

cache:
  - C:\projects\ezWebSockify.deps\include

