version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

build:
  project: platform/windows/ezWebSockify.sln

# scripts to run before build
before_build:

